baseURL = "https://bgracz.github.io/"
title = "_techguy"
theme = ["PaperMod"]
languageCode = "en-us"  # Warto dodaÄ‡ dla SEO

[params]
  defaultTheme = "dark"
  ShowReadingTime = true
  disableThemeToggle = true
  paginate = 7
  author = "B"

[menu]
  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    url = "/posts/"
    weight = 10

  [[menu.main]]
    identifier = "about"
    name = "About me"
    url = "/about/"
    weight = 30

  [[menu.main]]
    identifier = "projects"
    name = "Projects"
    url = "/projects/"
    weight = 20

[taxonomies]
  category = "categories"
  tag = "tags"

# To jest kluczowe dla RSS i metadanych
[author]
  name = "B"
  email = "cod@er.com"