baseURL = "https://bgracz.github.io/"
title = "_techguy"
theme = ["PaperMod"]
disableKinds = ["RSS"]

[params]
  defaultTheme = "dark"
  ShowReadingTime = true
  disableThemeToggle = true
  paginate = 7

[menu]
  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    url = "/posts/"
    weight = 10

  [[menu.main]]
    identifier = "about"
    name = "About me"
    url = "/about/"
    weight = 30

  [[menu.main]]
    identifier = "projects"
    name = "Projects"
    url = "/projects/"
    weight = 20

[taxonomies]
  category = "categories"
  tag = "tags"

[author]
  name = "coder"  # Tutaj wpisz swoje imię lub nick
  email = "cod@er.com" # Opcjonalnie, ale RSS często tego wymaga
